name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/src/**/*"
      - "**/*.kts"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the application
        uses: ./.github/actions/build